name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              uses: borales/actions-yarn@v4
              id: yarn-install
              with:
                  cmd: install

            - name: Create builds
              id: create-builds
              run: python build.py

            - name: Read VERSION.md
              id: read_version
              run: |
                  VERSION_CONTENT=$(cat VERSION.md)
                  VERSION=$(echo "$VERSION_CONTENT" | grep -oP '(?<=Version )\d+(\.\d+)+')
                  DESCRIPTION=$(echo "$VERSION_CONTENT" | grep -oP '(?<=Description:\n)[\s\S]*')
                  echo "::set-output name=version::$VERSION"
                  echo "::set-output name=description::$DESCRIPTION"
              shell: bash

            - name: Make zip files
              run: |
                  mkdir Lecture-Master-chrome-v${{ steps.read_version.outputs.version }}
                  cp -r build/chrome* Lecture-Master-chrome-v${{ steps.read_version.outputs.version }}/
                  zip -r Lecture-Master-chrome-v${{ steps.read_version.outputs.version }}.zip Lecture-Master-chrome-v${{ steps.read_version.outputs.version }}/

                  mkdir Lecture-Master-firefox-v${{ steps.read_version.outputs.version }}
                  cp -r build/* Lecture-Master-firefox-v${{ steps.read_version.outputs.version }}/
                  zip -r Lecture-Master-firefox-v${{ steps.read_version.outputs.version }}.zip Lecture-Master-firefox-v${{ steps.read_version.outputs.version }}/
              working-directory: ${{ github.workspace }}

            - name: Create GitHub tag
              id: create_tag
              run: echo "::set-output name=tag::v${{ steps.read_version.outputs.version }}"

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      Lecture-Master-chrome-v${{ steps.read_version.outputs.version }}.zip 
                      Lecture-Master-firefox-v${{ steps.read_version.outputs.version }}.zip
                  tag_name: ${{ steps.create_tag.outputs.tag }}
                  release_name: v${{ steps.read_version.outputs.version }}
                  body: ${{ steps.read_version.outputs.description }}
