name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              uses: borales/actions-yarn@v4
              id: yarn-install
              with:
                  cmd: install

            - name: Create build
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Zip build files
              run: |
                  mkdir build-zip
                  cp -r build/* build-zip/
                  zip -r build.zip build-zip/
              working-directory: ${{ github.workspace }}

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  files: build.zip
